# Mapping: package name → (display name, category)

TECH_MAP = {
    # Python frameworks
    "fastapi": ("FastAPI", "framework"),
    "flask": ("Flask", "framework"),
    "django": ("Django", "framework"),
    "streamlit": ("Streamlit", "framework"),
    "gradio": ("Gradio", "framework"),
    "pydantic": ("Pydantic", "framework"),
    "pydantic-settings": ("Pydantic", "framework"),
    "uvicorn": ("Uvicorn", "framework"),
    "gunicorn": ("Gunicorn", "framework"),
    "celery": ("Celery", "framework"),
    "httpx": ("HTTPX", "framework"),
    "aiohttp": ("aiohttp", "framework"),
    # JS frameworks
    "react": ("React", "framework"),
    "react-dom": ("React", "framework"),
    "next": ("Next.js", "framework"),
    "vue": ("Vue.js", "framework"),
    "express": ("Express", "framework"),
    "tailwindcss": ("Tailwind CSS", "framework"),
    "vite": ("Vite", "framework"),
    "zustand": ("Zustand", "framework"),
    "@tanstack/react-query": ("TanStack Query", "framework"),
    "react-query": ("TanStack Query", "framework"),
    "zod": ("Zod", "framework"),
    # AI/ML
    "tensorflow": ("TensorFlow", "ai_ml"),
    "torch": ("PyTorch", "ai_ml"),
    "torchvision": ("PyTorch", "ai_ml"),
    "scikit-learn": ("Scikit-learn", "ai_ml"),
    "sklearn": ("Scikit-learn", "ai_ml"),
    "pandas": ("Pandas", "ai_ml"),
    "polars": ("Polars", "ai_ml"),
    "numpy": ("NumPy", "ai_ml"),
    "scipy": ("SciPy", "ai_ml"),
    "matplotlib": ("Matplotlib", "ai_ml"),
    "seaborn": ("Seaborn", "ai_ml"),
    "plotly": ("Plotly", "ai_ml"),
    "ultralytics": ("YOLO", "ai_ml"),
    "yolov5": ("YOLO", "ai_ml"),
    "opencv-python": ("OpenCV", "ai_ml"),
    "opencv-python-headless": ("OpenCV", "ai_ml"),
    "cv2": ("OpenCV", "ai_ml"),
    "transformers": ("Transformers", "ai_ml"),
    "langchain": ("LangChain", "ai_ml"),
    "openai": ("OpenAI SDK", "ai_ml"),
    "anthropic": ("Anthropic SDK", "ai_ml"),
    "groq": ("Groq SDK", "ai_ml"),
    "huggingface-hub": ("HuggingFace", "ai_ml"),
    "xgboost": ("XGBoost", "ai_ml"),
    "lightgbm": ("LightGBM", "ai_ml"),
    "statsmodels": ("Statsmodels", "ai_ml"),
    "pillow": ("Pillow", "ai_ml"),
    "spacy": ("spaCy", "ai_ml"),
    "nltk": ("NLTK", "ai_ml"),
    "keras": ("Keras", "ai_ml"),
    # Database
    "sqlalchemy": ("SQLAlchemy", "database"),
    "psycopg2": ("PostgreSQL", "database"),
    "psycopg2-binary": ("PostgreSQL", "database"),
    "asyncpg": ("PostgreSQL", "database"),
    "pymongo": ("MongoDB", "database"),
    "redis": ("Redis", "database"),
    "firebase-admin": ("Firebase", "database"),
    "firebase": ("Firebase", "database"),
    "firestore": ("Firestore", "database"),
    "supabase": ("Supabase", "database"),
    "prisma": ("Prisma", "database"),
    "mongoose": ("MongoDB", "database"),
    "sqlite3": ("SQLite", "database"),
    "alembic": ("Alembic", "database"),
    # Tools (detected via files, not packages)
    "docker": ("Docker", "tool"),
    "github-actions": ("GitHub Actions", "tool"),
    "git": ("Git", "tool"),
    "playwright": ("Playwright", "tool"),
    "selenium": ("Selenium", "tool"),
    "pytest": ("Pytest", "tool"),
    "jest": ("Jest", "tool"),
    "eslint": ("ESLint", "tool"),
    "ruff": ("Ruff", "tool"),
    "mypy": ("MyPy", "tool"),
    "webpack": ("Webpack", "tool"),
    # Messaging / API
    "python-telegram-bot": ("Telegram Bot API", "framework"),
    "telebot": ("Telegram Bot API", "framework"),
    "aiogram": ("Telegram Bot API", "framework"),
    "slack-sdk": ("Slack SDK", "framework"),
    "discord.py": ("Discord.py", "framework"),
    "beautifulsoup4": ("BeautifulSoup", "tool"),
    "bs4": ("BeautifulSoup", "tool"),
    "scrapy": ("Scrapy", "tool"),
    "requests": ("Requests", "tool"),
}

# GitHub topics → (display name, category)
TOPIC_MAP = {
    "python": ("Python", "linguaggio"),
    "javascript": ("JavaScript", "linguaggio"),
    "typescript": ("TypeScript", "linguaggio"),
    "react": ("React", "framework"),
    "nextjs": ("Next.js", "framework"),
    "fastapi": ("FastAPI", "framework"),
    "docker": ("Docker", "tool"),
    "machine-learning": ("Machine Learning", "ai_ml"),
    "deep-learning": ("Deep Learning", "ai_ml"),
    "computer-vision": ("Computer Vision", "ai_ml"),
    "artificial-intelligence": ("AI", "ai_ml"),
    "data-science": ("Data Science", "ai_ml"),
    "nlp": ("NLP", "ai_ml"),
    "firebase": ("Firebase", "database"),
    "postgresql": ("PostgreSQL", "database"),
    "mongodb": ("MongoDB", "database"),
}

# GitHub language → display name
LANG_DISPLAY = {
    "Python": "Python",
    "JavaScript": "JavaScript",
    "TypeScript": "TypeScript",
    "Shell": "Shell",
    "HTML": "HTML",
    "CSS": "CSS",
    "Dockerfile": "Docker",
    "Go": "Go",
    "Rust": "Rust",
    "Java": "Java",
    "Kotlin": "Kotlin",
    "C": "C",
    "C++": "C++",
    "C#": "C#",
    "Ruby": "Ruby",
    "PHP": "PHP",
    "Swift": "Swift",
    "Dart": "Dart",
    "R": "R",
    "Jupyter Notebook": "Jupyter",
    "HCL": "Terraform",
    "Makefile": "Make",
}

LANG_EXCLUDE = {"Procfile", "Batchfile", "Nix", "Nunjucks", "EJS", "Pug"}

CATEGORIES = {
    "linguaggio": {"label": "LANGUAGES", "color": "#3fb950", "bg": "#1a3a2a"},
    "framework": {"label": "FRAMEWORK", "color": "#388bfd", "bg": "#1a2a3a"},
    "ai_ml": {"label": "AI / ML", "color": "#e6861a", "bg": "#3a2a1a"},
    "database": {"label": "DATABASE", "color": "#bc8cff", "bg": "#2a1a3a"},
    "tool": {"label": "TOOLS", "color": "#8b949e", "bg": "#1c2128"},
}
